### ISSUE TITLE
Ability to Open Two Emoji Select Windows

### ISSUE THREAD

**Issue by Blakemcw** [amass-social/website-v1#11]
**Current Behavior:**
When a user opens an \<EmojiSelect> window on the feed, they are able to click other buttons to open more \<EmojiSelect> windows.

**Expected Behavior:**
The user should only be able to have one \<EmojiSelect> window open at any given time.

**Example:**
![emoji-select-bug](https://user-images.githubusercontent.com/12144817/91931518-8e038180-ec98-11ea-9c80-80832bd90da9.gif)

**Comment by darrendawson** [comment]
The background div behind the popup that covers the screen should have a z-index above the emoji at the bottom, which would make it unclickable
